pub const ESC = trust $ echo -e "\x1B" $ 
pub const WHITE = "{ESC}[38;5;255m"
pub const BLACK = "{ESC}[38;5;0m"

pub const RED = "{ESC}[38;5;1m"
pub const RED_BG = "{ESC}[48;5;1m"
pub const RED_UNDERLINE = "{ESC}[4;58:5:1m"

pub const GREEN = "{ESC}[38;5;2m"
pub const GREEN_BG = "{ESC}[48;5;2m"
pub const GREEN_UNDERLINE = "{ESC}[4;58:5:2m"

pub const YELLOW = "{ESC}[38;5;214m"
pub const YELLOW_BG = "{ESC}[48;5;214m"
pub const YELLOW_UNDERLINE = "{ESC}[4;58:5:2m"

pub const BLUE = "{ESC}[38;5;4m"
pub const BLUE_BG = "{ESC}[48;5;4m"
pub const BLUE_UNDERLINE = "{ESC}[4;58:5:4m"

pub const MAGENTA = "{ESC}[38;5;5m"
pub const MAGENTA_BG = "{ESC}[48;5;5m"
pub const MAGENTA_UNDERLINE = "{ESC}[4;58:5:5m"

pub const CYAN = "{ESC}[38;5;38m"
pub const CYAN_BG = "{ESC}[48;5;38m"
pub const CYAN_UNDERLINE = "{ESC}[4;58:5:38m"

pub const GRAY = "{ESC}[38;5;241m"
pub const GRAY_BG = "{ESC}[48;5;241m"
pub const GRAY_UNDERLINE = "{ESC}[4;58:5:241m"

pub const PURPLE = "{ESC}[38;5;63m"
pub const PURPLE_BG = "{ESC}[48;5;63m"
pub const PURPLE_UNDERLINE = "{ESC}[4;58:5:63m"

pub const NC = "{ESC}[0m"
pub const BOLD = "{ESC}[1m"
pub const DIM = "{ESC}[2m"
pub const UNDERLINE = "{ESC}[4m"


pub fun rgb(r: Int, g: Int, b: Int): Text {
    return "{ESC}[38;2;{r};{g};{b}m"
}

pub fun rgb_bg(r: Int, g: Int, b: Int): Text {
    return "{ESC}[48;2;{r};{g};{b}m"
}

pub fun cursor_home(): Null {
    trust $ printf "{ESC}[H" $
}

pub fun cursor_move(rows: Int, cols: Int): Null {
    trust $ printf "{ESC}[{rows};{cols}H" $
}

pub fun cursor_up(rows: Int): Null {
    trust $ printf "{ESC}[{rows}A" $
}

pub fun cursor_down(rows: Int): Null {
    trust $ printf "{ESC}[{rows}B" $
}

pub fun cursor_right(cols: Int): Null {
    trust $ printf "{ESC}[{cols}C" $
}

pub fun cursor_left(cols: Int): Null {
    trust $ printf "{ESC}[{cols}D" $
}

pub fun cursor_save(): Null {
    trust $ printf "{ESC}7" $
}

pub fun cursor_restore(): Null {
    trust $ printf "{ESC}8" $
}

pub fun cursor_position(): [Int] {
    let row = 0;
    let col = 0;
    trust $
        stty -echo
        printf "{ESC}[6n"
        read -s -d\[ _
        IFS=';' read -d R {nameof(row)} {nameof(col)}
        stty echo
    $
    return [row, col]
}

pub fun print_prefix(style: Text, string: Text, color: Text, color_bg: Text): Text {
    if {
        style == "minimal": return "{BOLD}{color}{string}{NC}"
        style == "classic": return "{BOLD}{color}[{string}]{NC}"
        style == "inverted": return "{GRAY_BG}{BOLD}{color} {string} {NC}"
        else: return "{color_bg}{WHITE}{BOLD} {string} {NC}"
    }
}

pub const PREFIX_FORMAT = "default";
#[allow_public_mutable]
pub let TIMESTAMP_FORMAT = "%d/%m/%y %H:%M:%S";

#[allow_public_mutable]
pub let ERROR_FORMAT = "";
#[allow_public_mutable]
pub let LOG_FORMAT = "";
#[allow_public_mutable]
pub let SUCCESS_FORMAT = "";
#[allow_public_mutable]
pub let WARN_FORMAT = "";
pub const LINES = 0;
pub const COLUMNS = 0;


// Initialise $LINES and $COLUMNS for non-interactive bash, other shells load them by default
trust $ 
[[ "{shellname()}" == "bash" ]] && shopt -s checkwinsize && (:); 
{nameof(LINES)}="\$LINES"
{nameof(COLUMNS)}="\$COLUMNS" 
$
